import { chromium, devices } from 'playwright-core';
const out = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ ...devices['iPhone 14 Pro'], colorScheme: 'dark' });
const p = await ctx.newPage();
const errors = [];
p.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await p.waitForSelector('.hero', { timeout: 60000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: out + '/01-sdca.png' });
await p.evaluate(() => document.querySelector('.screen').scrollTo(0, 560));
await p.waitForTimeout(400);
await p.screenshot({ path: out + '/02-sdca-rainbow.png' });
await p.click('text=Composite Risk >> nth=0'); await p.waitForTimeout(400);
await p.screenshot({ path: out + '/03-sdca-risk.png' });
await p.click('text=Accum/Dist'); await p.waitForTimeout(600);
await p.screenshot({ path: out + '/04-sdca-curve.png' });
await p.evaluate(() => document.querySelector('.screen').scrollTo(0, 1250));
await p.waitForTimeout(400);
await p.screenshot({ path: out + '/05-sdca-backtest.png' });
await p.click('.tabbar button:nth-child(2)'); await p.waitForTimeout(800);
await p.screenshot({ path: out + '/06-rsps.png' });
await p.evaluate(() => [...document.querySelectorAll('.screen')].find((s) => s.offsetParent !== null || s.getClientRects().length)?.scrollTo(0, 700));
await p.waitForTimeout(400);
await p.screenshot({ path: out + '/07-rsps-inputs.png' });
await p.click('.tabbar button:nth-child(3)'); await p.waitForTimeout(500);
await p.click('.fab'); await p.waitForTimeout(500);
await p.keyboard.type('Plan DCA na październik');
await p.keyboard.press('Enter');
await p.keyboard.type('Composite risk 43.6% — HOLD, czekam na strefę akumulacji.');
await p.keyboard.press('Enter');
await p.click('.fmt-bar button:nth-child(2)');
await p.keyboard.type('Sprawdzić LTPI');
await p.keyboard.press('Enter');
await p.keyboard.type('Uruchomić skan RSPS');
await p.waitForTimeout(500);
await p.screenshot({ path: out + '/08-note-editor.png' });
await p.click('.editor-top .text-btn'); await p.waitForTimeout(700);
await p.screenshot({ path: out + '/09-notes.png' });
await p.click('.tabbar button:nth-child(4)'); await p.waitForTimeout(1500);
await p.screenshot({ path: out + '/10-excel.png' });
await p.click('text=Nowy skoroszyt'); await p.waitForTimeout(1200);
const fx = '.fx input';
const put = async (v) => { await p.click(fx); await p.fill(fx, v); await p.press(fx, 'Enter'); await p.waitForTimeout(120); };
for (const v of ['Aktywo', 'BTC', 'ETH', 'SOL', 'Razem']) await put(v);
await p.click('.sheet-tabs button.on'); // no-op focus
// column B
await p.evaluate(() => {});
const tapCell = async (r, c) => { const g = await p.$('.grid-canvas'); const bb = await g.boundingBox(); await p.mouse.click(bb.x + 44 + 92 * c + 30, bb.y + 26 + 30 * r + 12); await p.waitForTimeout(400); };
await tapCell(0, 1);
for (const v of ['Wartość', '61000', '24000', '15000', '=SUM(B2:B4)']) await put(v);
await tapCell(0, 2);
for (const v of ['Udział', '=B2/$B$5', '=B3/$B$5', '=B4/$B$5', '=SUM(C2:C4)']) await put(v);
await tapCell(1, 2);
await p.waitForTimeout(500);
await p.screenshot({ path: out + '/11-excel-sheet.png' });
console.log(JSON.stringify(errors, null, 1));
await b.close();
