import { chromium, devices } from 'playwright-core';
const out = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ ...devices['iPhone 14 Pro'], colorScheme: 'dark' });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await p.waitForSelector('.hero', { timeout: 60000 });
await p.click('.tabbar button:nth-child(2)'); await p.waitForTimeout(2500);
await p.screenshot({ path: out + '/r1.png' });
await p.evaluate(() => { const el = [...document.querySelectorAll('.eyebrow')].find(e => e.textContent.includes('Piramida')); const sc = el.closest('.screen'); sc.scrollTo(0, el.getBoundingClientRect().top + sc.scrollTop - 110); });
await p.waitForTimeout(400); await p.screenshot({ path: out + '/r2.png' });
await p.click('button:has-text("Makro")'); await p.waitForTimeout(500);
await p.screenshot({ path: out + '/r3.png' });
await p.click('.sheet button:has-text("Pozytywny") >> nth=1'); await p.click('text=Zapisz ocenę'); await p.waitForTimeout(400);
await p.click('.stat:has-text("Dźwignia")'); await p.waitForTimeout(500);
await p.screenshot({ path: out + '/r4.png' });
console.log(errs);
await b.close();
