import { chromium, devices } from 'playwright-core';
const out = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ ...devices['iPhone 14 Pro'], colorScheme: 'dark' });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await p.waitForSelector('.hero', { timeout: 60000 });
await p.click('.tabbar button:nth-child(3)'); await p.waitForTimeout(2500);
await p.fill('.screen:visible .hero input', '10000'); await p.press('.screen:visible .hero input', 'Enter'); await p.waitForTimeout(800);
await p.screenshot({ path: out + '/g1.png' });
await p.click('text=Kupiłem według planu'); await p.waitForTimeout(800);
await p.screenshot({ path: out + '/g2.png' });
await p.evaluate(() => { const sc = [...document.querySelectorAll('.screen')].find(s => s.getClientRects().length); sc.scrollTo(0, 900); });
await p.waitForTimeout(400); await p.screenshot({ path: out + '/g3.png' });
await p.click('.tabbar button:nth-child(4)'); await p.waitForTimeout(500);
await p.click('.fab'); await p.waitForTimeout(500);
await p.click('.editor-top .text-btn'); await p.waitForTimeout(300);
await p.click('.tabbar button:nth-child(2)'); await p.waitForTimeout(1500);
await p.click('button:has-text("Makro")'); await p.waitForTimeout(600);
await p.screenshot({ path: out + '/g4.png' });
console.log(errs);
await b.close();
